### ISSUE TITLE
No Tag (Version)

### ISSUE THREAD

**Issue by jetsup** [neph1/SsrFilter#2]
What is implementation script? The ome you've provided in the ```README``` page ```implementation 'com.github.neph1:SsrFilter:Tag'``` is not working or is not found.

**Comment by neph1** [comment]
I apparently can't check releases in the mobile app, but look there for the latest and replace 'Tag' with that. It should be 'v0.2' or something like that

**Comment by jetsup** [comment]
That should have been the first place I'd have looked. Thank you.
